#!/usr/bin/env bun
// Regenerates src/embedded.ts from the current set of profiles.
//
// embedded.ts must statically `import ... with { type: "file" }` every JSON the
// CLI might load, so Bun embeds them into the compiled standalone binary. Static
// import specifiers can't be globbed, so we codegen the file. Run this whenever
// a profile is added or removed (the binary build does it automatically).
import { readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const profiles = readdirSync(join(root, "src", "profiles"))
  .filter((f) => f.endsWith(".json"))
  .sort();

// Turn a profile filename into a valid JS identifier for the import binding.
const ident = (file: string) =>
  file
    .replace(/\.json$/, "")
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, "");

const imports = profiles
  .map((f) => `import ${ident(f)} from "./profiles/${f}" with { type: "file" };`)
  .join("\n");

const entries = profiles
  .map((f) => `  "${f.replace(/\.json$/, "")}": asPath(${ident(f)}),`)
  .join("\n");

const out = `// GENERATED by scripts/gen-embedded.ts: do not edit by hand.
//
// Embedded runtime data for the standalone (\`bun build --compile\`) binary.
//
// The CLI normally loads the tell registry and profiles from disk, relative to
// the module's own location. That works for \`bun src/cli.ts\`, for the Node
// \`dist/\` bundle (data is copied next to it), and for npm installs. It does NOT
// work inside a compiled binary, where there is no real filesystem next to the
// module. \`__dirname\` resolves into Bun's virtual \`/$bunfs/root\`.
//
// \`with { type: "file" }\` makes Bun embed each file into the binary and hands
// back a readable virtual path. The loaders fall back to these paths when the
// on-disk read misses. On a normal (non-compiled) run nothing reaches them.
import registryFile from "./tells/registry.json" with { type: "file" };
${imports}

// TypeScript types a \`type: "file"\` import as the parsed JSON object, but at
// runtime Bun resolves it to a string path. Coerce through \`unknown\`.
const asPath = (v: unknown): string => v as string;

/** Embedded path for the tell registry. */
export const EMBEDDED_REGISTRY_PATH = asPath(registryFile);

/** Embedded path for each built-in profile, keyed by profile id. */
export const EMBEDDED_PROFILE_PATHS: Record<string, string> = {
${entries}
};
`;

writeFileSync(join(root, "src", "embedded.ts"), out);
console.log(`generated src/embedded.ts (${profiles.length} profiles)`);
