// GENERATED by scripts/gen-embedded.ts: do not edit by hand.
//
// Embedded runtime data for the standalone (`bun build --compile`) binary.
//
// The CLI normally loads the tell registry and profiles from disk, relative to
// the module's own location. That works for `bun src/cli.ts`, for the Node
// `dist/` bundle (data is copied next to it), and for npm installs. It does NOT
// work inside a compiled binary, where there is no real filesystem next to the
// module. `__dirname` resolves into Bun's virtual `/$bunfs/root`.
//
// `with { type: "file" }` makes Bun embed each file into the binary and hands
// back a readable virtual path. The loaders fall back to these paths when the
// on-disk read misses. On a normal (non-compiled) run nothing reaches them.
import registryFile from "./tells/registry.json" with { type: "file" };
import consultingEnFormal from "./profiles/consulting-en-formal.json" with { type: "file" };
import essayEn from "./profiles/essay-en.json" with { type: "file" };
import essayRu from "./profiles/essay-ru.json" with { type: "file" };
import technicalEn from "./profiles/technical-en.json" with { type: "file" };

// TypeScript types a `type: "file"` import as the parsed JSON object, but at
// runtime Bun resolves it to a string path. Coerce through `unknown`.
const asPath = (v: unknown): string => v as string;

/** Embedded path for the tell registry. */
export const EMBEDDED_REGISTRY_PATH = asPath(registryFile);

/** Embedded path for each built-in profile, keyed by profile id. */
export const EMBEDDED_PROFILE_PATHS: Record<string, string> = {
  "consulting-en-formal": asPath(consultingEnFormal),
  "essay-en": asPath(essayEn),
  "essay-ru": asPath(essayRu),
  "technical-en": asPath(technicalEn),
};
